name: paystack_flutter
description: Flutter Plugin that enable users make Paystack payment with either Mobile Money, USSD or Card without web view.
version: 1.0.0
publish_to: 

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  http: ^1.1.2
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/
  uses-material-design: true
